spring:
  jpa:
    show-sql: true
---
spring:
  profiles: mysql
  jpa:
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
  datasource:
    url: jdbc:mysql://url/test?createDatabaseIfNotExist=true
    username: user
    password: password
    pool-size: 100
